### ISSUE TITLE
General roadmap

### ISSUE THREAD

**Issue by malleoz** [malleoz/mkw-startslide-ga#1]
Below is a list of tasks that must be completed in order to get this project working.

- [ ] In Rust, `extern "C" { pub fn physicsFn(); }` which will need to take inputs as an argument and return various parameters such as position, rotation, etc.
  - [ ] Define what values must be returned
  - [ ] Determine how to return values using primitive types defined in `cty`
  - [ ] Run test cases of physics function

- [ ] GA portion(C language)
  - [ ] Allow user to specify character and vehicle
    - [ ] Add a lookup table to retrieve necessary values
    - [ ] Pass this information to a constructor in the Rust portion so it doesn't need to constantly be exchanged
  - [ ] Allow seeded inputs (format will be each line having A,LR,DPad
  - [ ] Fitness function
    - [ ] Determine criteria
  - [ ] Mess with mutation settings
